export default {
  langs: ["ca", "es", "en"],
  ca: {
    locale: "ca-ES",
    langName: "Català",
    skipText: "Saltar al contingut principal",
    ariaPrimary: "Principal",
    ariaLang: "Canviar idioma",
    privacyPolicy: "Política de Privacitat",
    termsOfService: "Termes de Servei",
    switchLang: "Canviar idioma",
    information: "Informació",
    architecturePhotography: {text: "Fotografia d'Arquitectura", url: "/ca/fotografia-d-arquitectura/"},
    retailPhotography: { text: "Fotografia Comercial", url: "/ca/fotografia-comercial/" },
    exhibitions: {text: "Exposicions", url: "/ca/exposicions/"},
    about: {text: "Sobre mí", url: "/ca/sobre-mi/"},
    contact: {text: "Contacte", url: "/ca/contacte/"},
    cv: {text: "Currículum Vitae", url: "/ca/cv/"},
    contactForm: {
      title: "Formulari de Contacte",
      subtitle: "Parlem",
      text: "Tens un projecte en ment, alguna pregunta o simplement vols saludar? Deixa'm un missatge a sota i et respondré tan aviat com sigui possible.",
      name: "Nom",
      email: "Email",
      message: "Missatge",
      placeholderName: "p.e. Joan Torrents",
      placeholderEmail: "p.e. joan@exemple.com",
      placeholderMessage: "Explica'm el teu projecte...",
      send: "Enviar",
    },
    notFound: {
      title: "Ups! No em trobat res",
      message: "🫢 Ups! No em trobat allò que cercaves.",
      homeLink: "Tornar a l'inici",
      alt: "Una sabata vella coberta de molsa, el terra és cobert de fulles seques amb alguna que altra fulla verda.",
    },
    footer: {
      copyrightNotice: `© ${new Date().getFullYear()} Pau Guerrero`,
      byLine: "Fotografia d'Arquitectura i Paisatge",
      basedIn: "Amb base a Barcelona, Espanya — Disponible a nivell mundial",
      tagline: {
        retail: "Fotografia d'Arquitectura del Retail",
        arch: "Fotografia d'Arquitectura",
        exhibit: "Exposicions de Fotografia Fine Art",
      },
    },
  },
  es: {
    locale: "es-ES",
    langName: "Castellano",
    skipText: "Saltar al contenido principal",
    ariaPrimary: "Principal",
    ariaLang: "Cambiar el idioma",
    privacyPolicy: "Política de Privacidad",
    termsOfService: "Términos de Servicio",
    switchLang: "Cambiar idioma",
    information: "Información",
    architecturePhotography: {text: "Fotografía de Arquitectura", url: "/es/fotografia-de-arquitectura/"},
    retailPhotography: {  text: "Fotografía Comercial", url: "/es/fotografia-comercial/" },
    exhibitions: {text: "Exposiciones", url: "/es/exposiciones/"},
    about: {text: "Sobre mí", url: "/es/sobre-mi/"},
    contact: {text: "Contacto", url: "/es/contacto/"},
    cv: {text: "Curriculum Vitae", url: "/es/cv/"},
    contactForm: {
      title: "Formulario de Contacto",
      subtitle: "Hablemos",
      text: "¿Tienes un proyecto en mente, alguna pregunta o simplemente quieres saludar? Déjame un mensaje abajo y te responderé lo antes posible.",
      name: "Nombre",
      email: "Email",
      message: "Mensaje",
      placeholderName: "p.e. Juan Pérez",
      placeholderEmail: "p.e. juan@example.com",
      placeholderMessage: "Cuéntame acerca de tu proyecto...",
      send: "Enviar",
    },
    notFound: {
      title: "Ups! No hemos encontrado nada",
      message: "🫢 Ups! No hemos encontrado aquello que andabas buscando.",
      homeLink: "Regresar al inicio",
      alt: "Un zapato viejo cubierto de musgo, el suelo esta cubierto de hojas secas, algunas ramas de hierba verde alrededor.",
    },
    footer: {
      copyrightNotice: `© ${new Date().getFullYear()} Pau Guerrero`,
      byLine: "Fotografía de Arquitectura y Paisaje",
      basedIn: "Con base en Barcelona, España — Disponible a nivel mundial",
      tagline: {
        retail: "Fotografía de Arquitectura del Retail",
        arch: "Fotografía de Arquitectura",
        exhibit: "Exposiciones de Fotografía Fine Art",
      },
    },
  },
  en: {
    locale: "en-GB",
    langName: "English",
    skipText: "Jump to main content",
    ariaPrimary: "Primary",
    ariaLang: "Change language",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    switchLang: "Switch language",
    information: "Information",
    architecturePhotography: {text: "Architecture Photography", url: "/en/architecture-photography/"},
    retailPhotography: {text: "Luxury Retail Photography", url: "/en/luxury-retail-photography/"},
    exhibitions: {text: "Exhibitions", url: "/en/exhibitions/"},
    about: {text: "About", url: "/en/about/"},
    contact: {text: "Contact", url: "/en/contact/"},
    cv: {text: "Curriculum Vitae", url: "/en/cv/"},
    contactForm: {
      title: "Contact Form",
      subtitle: "Let's Connect",
      text: "Have a project in mind, a question, or just want to say hi? Drop a line below and I'll get back to you as soon as possible.",
      name: "Name",
      email: "Email",
      message: "Message",
      placeholderName: "e.g. John Mercer",
      placeholderEmail: "e.g. john@example.com",
      placeholderMessage: "Tell me about your project...",
      send: "Send",
    },
    notFound: {
      title: "Oops! Not Found",
      message: "🫢 Ooops! We haven't found what you were looking for.",
      homeLink: "Back to home",
      alt: "An old shoe covered in moss, the ground is covered in brown dry leaves, some green ivy branches around.",
    },
    footer: {
      copyrightNotice: `© ${new Date().getFullYear()} Pau Guerrero.`,
      byLine: "Architecture & Landscape Photography",
      basedIn: "Based in Barcelona, Spain — Available Worldwide",
      tagline: {
        retail: "Luxury Retail Architecture Photography",
        arch: "Architecture Photography",
        exhibit: "Fine Art Photography Exhibitions",
      },
    },
  },
};
